[package]
name = "filesystem"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
thiserror = { workspace = true }
memmap2 = "0.9"
flate2 = "1.1"
bzip2 = "0.6"
util = { path = "../util" }