[package]
name = "filesystem"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
bzip2 = "0.6"
flate2 = "1.1"
memmap2 = "0.9"
thiserror = { workspace = true }
tokio-util = { workspace = true }
util = { path = "../util" }