[package]
name = "game"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
config = { workspace = true }
filesystem = { path = "../filesystem" }
net = { path = "../net" }
serde = { workspace = true }
strum = "0.27"
strum_macros = "0.27"
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
util = { path = "../util" }