[workspace]
members = ["filesystem", "game", "js5", "util"]
resolver = "2"

[workspace.package]
authors = ["Tom LeGodais <tomlegodais@gmail.com>"]
edition = "2024"

[workspace.dependencies]
anyhow = "1"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
