[package]
name = "util"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
num-bigint = "0.4"
num-traits = "0.2"
tokio-util = { workspace = true }
bytes = "1.11.0"