[package]
name = "js5"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
filesystem = { path = "../filesystem" }
tokio = { workspace = true }
thiserror = { workspace = true }